import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Raleway } from "next/font/google";

import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { Header, TopBanner } from "@/components";

const outfit = Outfit({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "800", "900"],
  variable: "--font-outfit",
});

const raleway = Raleway({
  subsets: ["latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "800", "900"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${raleway.variable} antialiased`}>
        <TopBanner />
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
